version: '3.1'

services:
 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_dump:/docker-entrypoint-initdb.d:z
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: gd4_9523_c
      MYSQL_USER: BlibliSQL
      MYSQL_PASSWORD: teo12345
    ports:
      - 3306:3306
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.56.106:24224
        tag: database-future
      

  adminer:
    image: adminer
    ports:
      - 8080:8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.56.106:24224
        tag: adminer
  
  php:
    image: blibliphp
    volumes:
      - ./app:/app
      - phpsession:/tmp
    working_dir: /app
    environment:
      - HOSTNAME=db:3306
      - USERNAME=BlibliSQL
      - PASSWORD=teo12345
      - DBNAME=gd4_9523_c
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.56.106:24224
        tag: php

  web:
    image: vultr-nginx
    volumes: 
      - ./app:/app
    depends_on:
      - php
    ports:
      - 80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.56.106:24224
        tag: nginx-web

  loadbalancer: 
    image: nginx:latest
    ports:
      - 80:80
    volumes:
    - './nginx/nginx.conf:/etc/nginx/nginx.conf' 
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.56.106:24224
        tag: nginx-loadbalancer
  
volumes:
  phpsession:
