version: '3.1'

services:
 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_dump:/docker-entrypoint-initdb.d:z
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: gd4_9523_c
      MYSQL_USER: BlibliSQL
      MYSQL_PASSWORD: teo12345
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080
  
  php:
    image: blibliphp
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - HOSTNAME=db:3306
      - USERNAME=BlibliSQL
      - PASSWORD=teo12345
      - DBNAME=gd4_9523_c

  web:
    image: vultr-nginx
    volumes: 
      - ./app:/app
    depends_on:
      - php
    ports:
      - 80

  loadbalancer: 
    image: nginx:latest
    ports:
      - 80:80
    volumes:
    - './nginx/nginx.conf:/etc/nginx/nginx.conf' 
    
